### ISSUE TITLE
Swift 3 Unbox dictionary at seems to stop working?

### ISSUE THREAD

**Issue by terenzeyuen** [JohnSundell/Unbox#112]
This line used to work but not anymore, couldn't find a replacement?

 try Unbox(json, at: "jobOpenings")

**Comment by andreyz** [comment]
I think it's just the example in README is obsolete. If you look through the source, that method is no longer present.

**Comment by terenzeyuen** [comment]
Thanks @andreyz I think this was added here:
https://github.com/JohnSundell/Unbox/issues/73

But might not be migrated to swift3? Not sure what's going to happen as I have many projects using this custom path feature. @JohnSundell @clayellis

**Comment by JohnSundell** [comment]
@terenzeyuen @andreyz The reason this method doesn't exist on the `swift3` branch is because it was implemented on `master` after the branch was cut. So we'll need to merge `master` into `swift3` (and probably do some manual migration of code). I'll see if I can find some time to do that tonight or within the next few days :)

**Comment by terenzeyuen** [comment]
Superb!

**Comment by JohnSundell** [comment]
There we go, `master` has been merged into `swift3` - should solve the problem - otherwise let me know :)

**Comment by terenzeyuen** [comment]
Perfect, thanks @JohnSundell
