### ISSUE TITLE
enums usage unclear

### ISSUE THREAD

**Issue by tcurdt** [JohnSundell/Unbox#116]
The example has

```
enum SpaceShipType: Int {
    case Apollo
    case Sputnik
}

extension SpaceShipType: UnboxableEnum {
    static func unboxFallbackValue() -> SpaceShipType {
        return .Apollo
    }
}
```
Why do I need to provide a fallback value? It does not make any sense that spaceships are `Apollo` by default. I would rather have it fail it the value is missing or not a valid enum.

And how about this use case?

```
enum SpaceShipType: Int {
    case Apollo
    case Sputnik
}

struct SpaceShipOwner {
    let spaceships: [SpaceShipType]
}
```

The number of spaceships (=length of the array) should be 0..n

**Comment by tcurdt** [comment]
This almost does the right thing - except that it needs the default value

```
extension SpaceShipOwner: Unboxable {
    init(unboxer: Unboxer) {
        spaceships = unboxer.unbox(key: "spaceships") ?? []
    }
}
```

**Comment by JohnSundell** [comment]
@tcurdt As the documentation for `unboxFallbackValue()` states:
```
The value to use for required properties if unboxing failed. Typically a dummy value.
```
the fallback value is only used to be able to exit out of initializers without requiring every model to do its own error handling. Since Swift requires all non-optional properties to be initialized during an initializer, the fallback value is used as a "dummy" value, while internally Unbox marks the process as being failed - and at the end of the process an error will be thrown, just as you'd expect.

**Comment by tcurdt** [comment]
@JohnSundell would you agree that's a dirty hack? :)

Why not do it like this:

```
extension SpaceShipOwner {
    init(unboxer: Unboxer) throws {
        spaceships = try unboxer.unbox("spaceships")
    }
}
```

No falllback value, no special error handling. That feels way more "swifty" to me.

**Comment by JohnSundell** [comment]
Yeah, I agree that it's somewhat hacky by modern Swift standards. Unbox was originally written for Swift 1, so this mechanism has been around since then. But we should totally switch to using `throws` instead, like you say, it's a lot cleaner and more "swifty" :)
