### ISSUE TITLE
Regarding the 'throwing' approach

### ISSUE THREAD

**Issue by sasikiran** [JohnSundell/Unbox#133]
When I have break on "All Exceptions" turned on in my Xcode project, Unbox breaks at Optional.orThrow(). For a project that has many models and hence in turn many parameters that need to be unboxed, Xcode breaks at breakpoint several times. 
If I have to catch a mysterious exception in the project, I have to do the turn on and turn off breakpoint dance for Unbox. 

I started to wonder if there is there a way where I could not break on Unbox exceptions but break at everything else in my project? This also brings the question why did Unbox chose the try and break pattern?

**Comment by JohnSundell** [comment]
Hey @sasikiran! Are you sure you haven't turned on a `Swift Error Breakpoint`? Unbox does not generate exceptions, but rather throws Swift errors, which is the idiomatic standard for dealing with errors in Swift (it's used all throughout the standard library).

Before `2.0` Unbox used to deal with errors in a custom way, by holding state in `Unboxer`. This provided a nice way to deal with errors before `Swift 2`, but ever since the `do try catch` pattern was introduced it has become the standard way of dealing with errors, and enabled a much simpler implementation of Unbox - and a cleaner, more Swifty API.
