### ISSUE TITLE
Custom error reporting

### ISSUE THREAD

**Issue by aj1310** [JohnSundell/Unbox#136]
On Unbox 2.1, I was using the invalid key error of UnboxError to declare there was something off in the semantic of the unboxed value e.g. Coordinate where latitude is a Double between -90  and 90.

On Unbox 2.2, I have found out that this is now a private method. What is the "official" way to provide custom errors? Or is this out of scope?

Thanks

**Comment by JohnSundell** [comment]
@aj1310 Yeah, turns out way more people was using the different error cases in `UnboxError` than I thought, so I was mistaken to remove it. Bringing it back in `2.2.1` though, hopefully I can release it tonight :)

**Comment by aj1310** [comment]
I can create a quick PR for this feature as a public extension for UnboxError with static methods if you are interested.

**Comment by JohnSundell** [comment]
@aj1310 Absolutely! Had to take care of a much of other stuff for the last few days so haven't had time to look at it yet :( But go for it! 👍

**Comment by aj1310** [comment]
Should all error types in UnboxPathError be exposed, or should it be scoped to semantic errors that a developer might throw in their custom logic? e.g. invalidValue

**Comment by JRG-Developer** [comment]
IMHO, consideration should be given to whether `UnboxPathError` should actually be exposed publicly. 

This allows the library consumer to decide what to do based on the type of error, instead of assuming the app can't ever handle it (which is what making this private does assume).

At the very least, I think `UnboxError` should have a _public_ initializer.

I couldn't come up with any good reasons for why this _shouldn't_ be public, so I've submitted PR #142 that simply changes this access specifier.

:]

**Comment by JohnSundell** [comment]
Fixed in [Unbox 2.3](https://github.com/JohnSundell/Unbox/releases/tag/2.3.0). I made `UnboxPathError` public and reverted `UnboxError` to be an `enum` (meaning that it can easily be created from outside). Thanks @JRG-Developer & @aj1310 for your work on this! 🚀
