### ISSUE TITLE
Better performance?

### ISSUE THREAD

**Issue by hartbit** [JohnSundell/Unbox#138]
Unbox is by far my favorite swift decoding library. But I've seen it affect performance on a few projects where I am decoding a few million objects. The following article [JSONShootout](https://github.com/bwhiteley/JSONShootout) does seem to imply that Unbox has a performance problem compared to others. I guess something can be done about it, especially as Marshal has a very similar API.

Any ideas?

**Comment by VivienGiraud** [comment]
Latest release increase performances, JSONShootout, IIRC, doesn't use Unbox 2.2.0.
https://github.com/JohnSundell/Unbox/releases/tag/2.2.0

**Comment by hartbit** [comment]
👌 nice, hadn't seen that release!

**Comment by JohnSundell** [comment]
Hi @hartbit!

First of all, very sorry for the slow response 😢 

Super happy to hear that Unbox is your favorite Swift JSON library 🎉 I sure want to make it not only the easiest to use JSON decoder, but also the fastest one. Currently, it's performing very well, but there are libraries (such as Marshal) that are faster still.

The main reason is that Unbox uses a lot of dynamism to enable all of its APIs (Unbox has quite a lot of powerful APIs that other decoders don't have, like infite nested collections, automatic mapping of `String` -> `Int`, etc). But the good news is that we can optimize this - to make sure that the code paths that don't require any dynamism are resolved as statically as possible. 👍

Many such improvements were made in Unbox `2.2.0`, as @VivienGiraud mentioned. And I (and you and the others in the Unbox community are of course very welcome to help out as well) will continue to improve Unbox to make it as fast as possible 🚀

I'm going to close this issue for now (hope you don't mind, if so - we'll reopen!), since Unbox doesn't really have a **performance problem** currently, and then we can open individual issues whenever a bottleneck is encountered, or when we discover something in dire need of optimization 😄

**Comment by hartbit** [comment]
@JohnSundell thanks for the great answer 👍
