### ISSUE TITLE
Unboxing an array of protocol types

### ISSUE THREAD

**Issue by Boerworz** [JohnSundell/Unbox#17]
Hey John!

Thanks for making it super simple to decode JSON :)

I've run across a problem with unboxing one of the models in my application, though. I'm using an `Item` protocol, which requires conforming classes to conform to the `Unboxable` protocol as well:

```swift
protocol Item: Unboxable {
    // ...
}
```

When trying to unbox a required array of `Item`s in one of the conforming classes, the unboxer fails:

```swift
class Group: Item {
    let children: [Item]
   
    required init(unboxer: Unboxer) {
        items = unboxer.unbox("items")
        // items is empty and unboxer.hasFailed is true
    }
}
```

After spending some time debugging, this seems to be caused by the call to `unboxer.unbox("items")` being statically dispatched to the `func unbox<T>(key: String) -> [T]` method at **Unbox.swift:290** instead of the `func unbox<T: Unboxable>(key: String) -> [T]` method at **Unbox.swift:351**.
This leads to `UnboxValueResolver.resolveOptionalValueForKey` trying to downcast the boxed value to `[Item]` instead of `[UnboxableDictionary]`, which unsurprisingly fails.
I've tried to modify the `func unbox<T>(key: String) -> [T]` method to check at runtime if the type `T` is `Unboxable` and act accordingly, but this seems nigh impossible.

As far as I can see, this is a limitation of Swift, not an Unbox issue, but it would be great if you could update the README with this gotcha :)

For completeness sake: In my application, I think I'm going to annotate the boxed values with a `type` value and then use that to decide at runtime what concrete `Item`-type to unbox as.

Cheers,
Tim

**Comment by Boerworz** [comment]
I should mention that I'm using Unbox 1.2.1.

**Comment by JohnSundell** [comment]
Hey Tim,

Happy you like Unbox :)

Yeah, you're right - nested types need to be concrete (such as `Struct`, `Class`, `Enum` etc) in order for Swift to be able to select the proper overload of `unbox()` to use. Since `Item` could refer to any implementation of the protocol, there's no way to select what type to initialize, so Swift falls back to the most generic implementation (with the return type `[T]`). I'm actually going to update that, so it works similar to how nested dictionaries work, only allowing `[T] where T: UnboxRawValueType` (new in Unbox 1.2.3). This would cause code like yours to fail at compile time instead of at runtime. I will also add some debugging tips to the `README`.

Your solution with a `type` value is a nice approach. Then you can use an intermediate `ItemData` structure that Unbox can decode for you, and then use the `type` value (which can be an `UnboxableEnum`) to transform it into the proper type.

**Comment by JohnSundell** [comment]
There you go, `README` updated with a "Debugging tips" section and you can now only use `unbox()` with an array return type of `T: Unboxable`, `T: UnboxableWithContext` or `T: UnboxableRawType` - so more of the type of errors that you encountered will be moved to compile time :) Thanks for bringing this issue to my attention :rocket: :+1:

**Comment by Boerworz** [comment]
Great updates! A compile time error is a lot better :) 
Thanks!
