### ISSUE TITLE
Parse an array of protocols

### ISSUE THREAD

**Issue by dalu93** [JohnSundell/Unbox#171]
I have a protocol as below

```swift
protocol Category: Unboxable {
   // bunch of properties
  // no Unbox init
}
```

Then I have an object which is `Unboxable` as well and has a property that is an array of `Category`.

```swift
struct Section: Unboxable {
  let categories: [Category]
  // others...

  init(unboxer: Unboxer) throws {
    categories = try unboxer.unbox(key: "categories")
  }
}
```

When trying to parse the `Section` structure I get this error
`"Invalid collection element type: Category. Must be UnboxCompatible or Unboxable."`

that it is thrown in `Unbox.swift:324`. The Unbox version is `2.4.0`.
Is there a way to solve this issue? Thanks

**Comment by JohnSundell** [comment]
Hi @dalu93!

This issue has been discussed quite a few times in the past (for example here: https://github.com/JohnSundell/Unbox/issues/25). The problem is that Swift cannot dispatch to an overload of `unbox` since it has no concrete type to use (it only knows that you're looking for `[Category]`, but not which implementation of `Category` to actually use).

I would suggest using a `type` property or something in the data, and then use the custom unboxing API to dispatch to the correct implementation of `init(unboxer:)`.

**Comment by dalu93** [comment]
@JohnSundell this is exactly what I wanted to get rid of by using protocols. Doesn't matter, luckily I have a `categoryType` value in the JSON which I can use to distinguish the type of items.

**Comment by JohnSundell** [comment]
@dalu93 Perfect 👍
