### ISSUE TITLE
Question: Future of Unbox given Codable

### ISSUE THREAD

**Issue by bhstrifork** [JohnSundell/Unbox#191]
What are the plans for the future of Unbox now that Swift 4 has `Codable`?

**Comment by JohnSundell** [comment]
Hi @bhstrifork 👋

That's a great question! 👍 I'm planning to keep working on both Unbox & Wrap for the foreseeable future, continuing to improve their APIs and make adjustments for new versions of Swift. Eventually they will probably start using `Codable` under the hood, and at some point they might simply become extensions on top of the `Codable` API, as it evolves and probably becomes more powerful.

But for now, I think Unbox/Wrap and `Codable` can definitely co-exist. So the developers of the over 3000 apps that rely on Unbox for their JSON needs don't have to worry, because it's not going away anytime soon 😉
