### ISSUE TITLE
Unbox json data twitter api Swift4

### ISSUE THREAD

**Issue by Huandv** [JohnSundell/Unbox#226]
Hi,
First, thanks for your work, this project is really cool :)

Im have problem when try get value some key of data.

Here is my data:

`{
    "created_at" = "Tue Jul 10 11:13:55 +0000 2018";
    text = "tests https://t.co/Tr48QVGXZ8";
    user =         {
        name = HuanCAO;
        "screen_name" = HuanCAO93;
    };
},
    {
    "created_at" = "Tue Jul 10 10:19:53 +0000 2018";
    text = "just setting up my Twitter Kitadaw";
    user =         {
        name = HuanCAO;
        "screen_name" = HuanCAO93;
    };
}`

This is what I'm doing:

`struct User: Unboxable {
    let text: String
    let created_at: String
    
    init(unboxer: Unboxer) throws {
        self.text = try unboxer.unbox(key: "text")
        self.created_at = try unboxer.unbox(key: "created_at")
    }
}`

`client.sendTwitterRequest(request) { (response, data, connectionError) -> Void in
    if connectionError != nil {
        print("Error: \(String(describing: connectionError))")
    }
    do {
        let user: User = try unbox(data: data!)
        print(user)
    } catch let jsonError as NSError {
        print("json error: \(jsonError.localizedDescription)")
    }
}`

This code has error: json error: The operation couldn’t be completed. (Unbox.UnboxError error 1.)

Hope you reply soon. Thank you so much!

**Comment by clayellis** [comment]
Hi @Huandv! Welcome to Unbox! Well, your first issue is that the data you're trying to Unbox isn't valid JSON. Did you get that from an actual API? I'll assume that at some point had a valid JSON response and printed it out and it got mangled or something — but I'm guessing it was originally in this format:

```
[
    {
        "created_at": "Tue Jul 10 11:13:55 +0000 2018",
        "text": "tests https://t.co/Tr48QVGXZ8",
        "user": {
            "name": "HuanCAO",
            "screen_name": "HuanCAO93",
        }
    },
    {
        "created_at": "Tue Jul 10 10:19:53 +0000 2018",
        "text": "just setting up my Twitter Kitadaw",
        "user": {
            "name": "HuanCAO",
            "screen_name": "HuanCAO93"
        }
    }
]
```

First of all, when Unboxing dates, you need to provide the unboxer a formatter so it knows how to parse the date string correctly. So the model you're trying to parse out might look something like this:

```swift
struct Model {
    let text: String
    let createdAt: Date
}

extension Model: Unboxable {
    init(unboxer: Unboxer) throws {
        text = try unboxer.unbox(key: "text")
        let formatter = DateFormatter()
        // Tue Jul 10 11:13:55 +0000 2018
        formatter.dateFormat = "E MMM d HH:mm:ss Z yyyy"
        createdAt = try unboxer.unbox(key: "created_at", formatter: formatter)
    }
}
```

Second, the JSON you're receiving is (I assume, with a bit of reconstructing) an array of `Model`s. So in order to parse the above json you need to ask to unbox an array of `Model`s, like so:

```swift
let data = json.data(using: .utf8)!

do {
    let models: [Model] = try unbox(data: data)
    print(models)
    print(models[0].text)
    print(models[0].createdAt)
} catch {
    print("JSON Error: \(error)")
}
```

I hope that helps! Feel free to ask any other questions you might have about that.

**Comment by Huandv** [comment]
Hi clayellis, thanks you so much!

**Comment by Huandv** [comment]
Hi @clayellis , thank you so much!
It's worked.

**Comment by clayellis** [comment]
@Huandv glad to help and glad it's working for you! Would you mind closing this issue?

**Comment by Huandv** [comment]
@clayellis yes !
