### ISSUE TITLE
Release 3.0 has a version mistake in .podspec

### ISSUE THREAD

**Issue by hechen** [JohnSundell/Unbox#236]
Hi, John

So appreciate your work on the amazing work. 

I find 3.0 Release has a version mismatch on the podspec file. 

``` ruby

Pod::Spec.new do |s|
  s.name         = "Unbox"
  s.version      = "2.5.0"         # <<<<<<  Mismatch
  s.summary      = "The easy to use Swift JSON decoder."
 
  # xxxxx

end

```

**Comment by DarkDust** [comment]
Same is true for 3.1.0.

**Comment by JohnSundell** [comment]
Hey @hechen, @DarkDust,

This is because of a chicken-and-egg problem when pushing to CocoaPods trunk - which requires you to release a version on GitHub before you're able to push your Podspec to the trunk. However, as long as you fetch Unbox from CocoaPods trunk, then the podspec in this repo doesn't really matter - since the updated version is stored with CocoaPods. But I've now updated `master` to contain the latest Podspec, in case you need that.
