### ISSUE TITLE
Support with failable initializers in Unboxer

### ISSUE THREAD

**Issue by AndreyPanov** [JohnSundell/Unbox#33]
I want to create struct like: 
```
struct User: Unboxable {

    let id: Int
    let name: String
    let avatar: NSURL?

    init?(unboxer: Unboxer) {
        if let idUW = unboxer.unbox("id") {
               id = unboxer.unbox("id")
       } else {
              return nil
       } 
       // over inits
    }
}
```
But I get the error `Non-failable initializer requirement 'init(unboxer:)' cannot be satisfied by a failable initializer ('init?')`.
Why is this feature not supported?
Thank you!

**Comment by JohnSundell** [comment]
Hi!

The good news is that Unbox takes care of this for you, so you don't need to fail an initializer manually. If Unbox can't decode a required property (like `id`) in this case, the Unboxer responsible for the decoding will be marked as `failed`, and `nil` will be returned from the `Unbox()` call that started the decoding process. So this code will be all you need:

```
struct User: Unboxable {
     let id: Int
     let name: String
     let avatar: NSURL?

     init(unboxer: Unboxer) {
          self.id = unboxer.unbox("id")
          self.name = unboxer.unbox("name")
          self.avatar = unboxer.unbox("avatar")
     }
}
```

Since `avatar` is an optional property, Unbox will not fail if its data is missing, but for `id` and `name` it will.

You can also manually fail an Unboxer, using the following APIs:
```
failForKey(key: String)
failForInvalidValue(invalidValue: Any?, forKey key: String)
```

Finally, you can also inspect if an Unboxer has failed (in case you don't want to perform any expensive custom operations if the decoding has failed anyway) using the `hasFailed` property.

**Comment by JohnSundell** [comment]
OK if I close this issue, or do you still need the failable initializer given the info above? :)

**Comment by AndreyPanov** [comment]
John, thank you for you answer!
I think you can close :)

**Comment by JohnSundell** [comment]
Cool :)
