### ISSUE TITLE
Properly unbox an array of different classes/models?

### ISSUE THREAD

**Issue by idevsoftware** [JohnSundell/Unbox#35]
Hi @JohnSundell. I've been using Unbox during the last few weeks for a new project I'm developing and it works great. Recently I came across a requirement which I'm not entirely sure how to tackle. As part of a JSON response I'm getting an array of dictionaries, each entry corresponding to a member of a local (Unboxable) class I have. However, the exact class type depends on a certain value in the response dictionary:

```
[
   {
        "type": "someClass",
        "common_property": "someValue",
        "some_property": "funnyValue"
    },
    {
        "type": "anotherClass",
        "common_property": "anotherValue",
        "another_property": "sadValue"
    }
]

```
What I want to achieve is to decode -- sorry, _Unbox_ -- the whole array on a single shot. So far I've failed to do so. It would be great to have some kind of way to tell Unbox to use a particular factory class method on a superclass to initialize and return an instance (which could be of a different subclass type, based on one of the given parameters), without having to resort to manually decode the retrieved data into a local dictionary and then cycle through it.

**Comment by JohnSundell** [comment]
Hi @idevsoftware! Sorry for the late reply. This fix should do it: https://github.com/JohnSundell/Unbox/commit/d0c1240d67f6dd964ab7871a0728480ae20850dc

I've expanded the `Custom Unboxing` API to cover arrays of dictionaries as well, so that you can get more fine-grained control over the unboxing process for each element. See the associated test for usage example.

Let me know if there are any other improvements that can be made :)

**Comment by idevsoftware** [comment]
👍👍👍
