### ISSUE TITLE
Make static method unboxerFromData() public

### ISSUE THREAD

**Issue by idevsoftware** [JohnSundell/Unbox#42]
Hi @JohnSundell, it's me again. 

Is there a hard reason why `unboxerFromData()` is a private static method? There are cases where it would be useful to have an `Unboxer` object instantiated and ready without immediately initializing an `Unboxable` object instance. I have one of such cases right now.

I am currently using a persistence model for my data (Realm in my particular case, but it could be Core Data or any other). Whenever I retrieve a JSON from the server, I would like to check first if there's an existing instance of that class on my persistent store and use it to update its properties with a given `Unboxer`, otherwise if there are no instances only then initialize a new one with the same `Unboxer`. Does it makes sense?

For what I've seen it's just a matter of moving `unboxerFromData()` out of its private extension on `Unboxer` and make it a public method instead. If you agree with this approach and think it could be a good idea/useful, I'd be more than glad to send a pull request for it.

Once again thank you for your time and great work on Unbox.

**Comment by idevsoftware** [comment]
Also related - `Unboxer`'s `init(dictionary, context)` should be public as well

**Comment by JohnSundell** [comment]
Hi @idevsoftware!

The reason both `Unboxer`'s initializer and the related static construction methods are private, is in order to guarantee that an instance of `Unboxer` is only used in a single unboxing process. Since `Unboxer` keeps state; the current data that is being unboxed and any error that occured - it only makes sense to be used in a single process - and if we allowed creation of them outside of the library - this mechanism might not work as intended.

For example; a developer would need to know exactly how `Unboxer` works, in order to know the above - and might accidentially reuse the same `Unboxer` in different unboxing processes, leading to errors that would potentially be hard to debug.

That being said; Unbox does offer a "Custom Unboxing" API to support the exact use case that you mention - if you have multiple sources of data (like Core Data, etc) that should be combined with the JSON data that is being unboxed. It gives you the flexibility of being able to gain full control over the unboxing process, while still guaranteeing that the mechanisms of `Unboxer` stays intact.

An example:

```
let model: Model = try Unboxer.performCustomUnboxingWithDictionary(dictionary, closure: {
    let unboxer = $0

    var model = Model()
    model.name = managedObject.name
    model.count = unboxer.unbox("count")

    return model
})
```

Check out the `README` for more information about the Custom Unboxing API.

Related discussions:
https://github.com/JohnSundell/Unbox/issues/27
https://github.com/JohnSundell/Unbox/issues/18

**Comment by idevsoftware** [comment]
Wow. I keep forgetting how powerful the custom unboxing API is. Thanks!
