### ISSUE TITLE
Unboxing an enum with two key payload

### ISSUE THREAD

**Issue by pavankataria** [JohnSundell/Unbox#45]
Take the following json payload: 
```
{   
    "id" : 1,
    "enum_value" : "North",
}
```
were id can range from -1, 1,2,3, and 4; mapped to None, North, East, South, and West respectively.

Then take the following enum I created:

```
enum CardinalDirection: Int, UnboxableEnum {
    case None = -1
    case North = 1
    case East = 2
    case South = 3
    case West = 4
 
    static func unboxFallbackValue() -> CardinalDirection {
        return .None
    }
}
```

How would unbox know how to take the ID and map accordingly to the correct case? Especially if the enum_value should be ignored?

**Comment by JohnSundell** [comment]
Either you just use the numeric value in `id`, like this:

```
struct Model: Unboxable {
    let direction: CardinalDirection

    init(unboxer: Unboxer) {
        self.direction = unboxer.unbox("id")
    }
}
```

or, you make `CardinalDirection` conform to `UnboxableByTransform` and use a transformation based on the string value and/or id value.

Swift automatically dispatches to the correct `Unboxer` overload because it has an implementation where `T: UnboxableEnum`, which uses `T.RawValue` (which it gets from `RawRepresentable`, that it extends) to map to the correct enum case.
