### ISSUE TITLE
Unbox nested array

### ISSUE THREAD

**Issue by maxday** [JohnSundell/Unbox#54]
Hi,

First, thanks for your work, this project is really cool :)

Is there a way to Unbox nested toys array ?
I would like to use something like 
    
    let arr : [Toy] = try UnboxOrThrow(data)

But is there a way to map nested array ?
Here is my sample data

    {
        "content": "Toys",
        "toys": [{
            "id": "12",
            "title": "superToy"
        }, {
            "id": "13",
            "title": "awesomeToy"
        }]
    }

This is what I'm doing for now (with Swifty)

    let json = JSON(data: data)
    let arrayToParse = try json["toys"].rawData()
    let arr : [Toy] = try UnboxOrThrow(arrayToParse)

**Comment by JohnSundell** [comment]
Hi @maxday, happy you like Unbox! :)

Sure, you can do this! All you need to do is wrap the array in an object (since your root data structure is a dictionary, not an array), and then you can just call `unboxer.unbox()` on the array and have Unbox automatically decode all of the dictionaries in the array into `Toy` instances. Like this:

```
struct ToyBox: Unboxable {
   let toys: [Toy]

   init(unboxer: Unboxer) {
      self.toys = unboxer.unbox("toys")
   }
}

struct Toy: Unboxable {
   let id: String
   let title: String

   init(unboxer: Unboxer) {
      self.id = unboxer.unbox("id")
      self.title = unboxer.unbox("title")
   }
}
```

Now you can unbox an array of `Toy` like this:

```
let toyBox: ToyBox = try Unbox(data)
let toys = toyBox.toys
```

You could've had Unbox return an array of `Toy` directly if your root data structure in your JSON was an array.

**Comment by maxday** [comment]
Cool :)
Thanks for your quick answer :D

**Comment by JohnSundell** [comment]
@maxday No problems, let me know if you run into any other issues 👍
