### ISSUE TITLE
More failed information.

### ISSUE THREAD

**Issue by RyogaK** [JohnSundell/Unbox#59]
Now there are top level key and value as `UnboxError.InvalidValue`.
However, often there is a case of the cause is there in under 2nd level.

e.g.
```
{
  hoge: {
    id: Int <- This is required, but there is no
  }
}
```
Unbox tell me just `hoge` is invalid. I hope to know `id` is missing.

**Comment by bre7** [comment]
How did you define your Unboxable model ? Since there's an object, you should use 2 structures to define it (The 2nd level could be a Dictionary also)

E.g. using 2 structs:
```swift
struct Hoge: Unboxable {
    let id: Int
    
    init(unboxer: Unboxer) {
        id = unboxer.unbox("id")
    }
}


struct Model: Unboxable {
    let hoge: Hoge
    
    init(unboxer: Unboxer) {
        hoge = unboxer.unbox("hoge")
    }
}


do {
    let model: Model = try Unbox(json)
    model.hoge // Hoge struct
    model.hoge.id // Int
    print(model)
} catch {
    print(error)
}
```

**Comment by JohnSundell** [comment]
We should totally improve the error reporting in this case. The error should ideally say something like:
```
Nested model Hoge for key "hoge" could not be decoded because the key "id" was missing.
```
Will work on that 👍

**Comment by RyogaK** [comment]
@bre7 Yes, I did it.
@JohnSundell Thanks. I tried to do that, in my fork, but I couldn't well...
I'm looking forward to that 😆

**Comment by JohnSundell** [comment]
Related to https://github.com/JohnSundell/Unbox/issues/64, we'll start work on this soon :)

**Comment by JohnSundell** [comment]
@RyogaK Error reporting is now a lot better (thanks to @Evertt), since https://github.com/JohnSundell/Unbox/pull/68. Let us know what you think!

**Comment by jakunico** [comment]
Guys, we're having some issues with the failed information when it happens in a nested object. To give an example, check out the following model:

```swift
struct User: Unboxable {
    
    let car: Car
    
    init(unboxer: Unboxer) {
        car = unboxer.unbox("car")
    }
    
}

struct Car: Unboxable {
    
    let paint: Paint
    
    init(unboxer: Unboxer) {
        paint = unboxer.unbox("paint")
    }
    
}

struct Paint: Unboxable {
    
    let color: String
    
    init(unboxer: Unboxer) {
        color = unboxer.unbox("incorrect-key!")
    }
    
}
```

Here you'll notice that the key for `Paint.color` is incorrect. When attempting to Unbox a `User` Dictionary, this is the failure information provided:

```
[Unbox error] Invalid values were encountered. Errors: Invalid value ({
    paint =     {
        color = blue;
    };
}) for key (car)
```

Even though that is correct, the information provided is not very useful in cases where the error happened deep into the hierarchy of objects or when you have a ton of attributes in your JSON.

Something like this would me much more useful I think:

```
Missing key "color" on "YourApp.Paint"
```

I attempted to debug this and found that the missing key is actually captured and added to `Unboxer.failureInfo` of the `Paint` struct. The problem is that the info is lost as the `failureInfo` of the topmost `Unboxer` instance is what is used.

A possible solution would be to append child `Unboxer.failureInfo` when a failure is detected in a nested object.

Let me know your thoughts, thanks in advance!

**Comment by garnett** [comment]
Tried to do it myself but apparently (as I understood it) whole error reporting should be reconsidered. 

I've seen discussion related to collecting of all errors in the array and I personally would prefer more **monadic** approach where Unbox fails as soon as it encounters the first error (it propagates it from leaf to the root gathering the context along the way to form nice errors as proposed above):

```
Missing key "color" on "YourApp.Paint"
```

**Comment by RyogaK** [comment]
I think this issue is done.
I'm very satisfied with current error reporting. Thanks a lot!
