### ISSUE TITLE
Compilation errors with Swift 2.1.1

### ISSUE THREAD

**Issue by eloquentbit** [JohnSundell/Unbox#66]
Hi John,
I've added Unbox to one of my projects but when I build it I obtain a series of error messages regarding Unbox.swift like 'ContextType is not a member type of T'
My Swift version is 2.1.1 and Xcode 7.2.1
Thank you
Luca

**Comment by JohnSundell** [comment]
Hi @eloquentbit, you'd have to use an older version of Unbox that was written for this version of Swift. The current release has been updated for Swift 2.2 and that's why you're seeing these errors. Try Unbox 1.3.1 (use the git tag `1.3.1`, or update your dependency manager manifest). Does that solve your problem?

**Comment by lp76** [comment]
Hi @JohnSundell, thanks for your help. I'll update my Swift version.

**Comment by eloquentbit** [comment]
Hi @JohnSundell, thanks for your help. I'll update my Swift version

**Comment by JohnSundell** [comment]
@eloquentbit No problems! 👍
