### ISSUE TITLE
When I include Unbox as a dependency in my Swift 3 project, I get the Swift 2 version

### ISSUE THREAD

**Issue by Evertt** [JohnSundell/Unbox#70]
I'm using the Swift Package Manager by the way.

**Comment by JohnSundell** [comment]
@Evertt Is there a way to get SPM to use a specific branch of a project (the `swift3` branch in this case)? If not, it doubt that it will be possible to use Unbox (or other non-Swift 3-only projects) until the launch of Swift 3 - where we can make a proper release that supports it. Very open for suggestions though :)

**Comment by Evertt** [comment]
Well what I've seen other packages do is that they match their major version-numbers to that of Swift. You could do that to. So have a 2.x version for Swift 2 and a 3.x version for Swift 3. Would you be okay with doing that?

**Comment by JohnSundell** [comment]
Not sure if I think making full-blown releases for a language version that is still in development is such a good idea actually :/ I do plan to bump Unbox to 2.0 once Swift 3 support is released, since it will be a major breaking change. However, I don't think the Swift 3 implementation is ready for release yet, both because of Unbox and because it's still a moving target. In the meantime, you can always make a release off your fork, and point the SPM to that. Would that be an OK workaround for now?

**Comment by Evertt** [comment]
Yes that would be okay for now. :-)

**Comment by JohnSundell** [comment]
Awesome :)
