### ISSUE TITLE
Use fallback value when unboxing enum

### ISSUE THREAD

**Issue by milancermak** [JohnSundell/Unbox#78]
Hi,
I'm thoroughly enjoying Unbox and Wrap combo. Very nice libs, thanks.

I ran into one issue though. Consider the following code:
```swift
class Event: Unboxable {
    enum Target: String, UnboxableEnum {
        case facebook, google, unknown

        static func unboxFallbackValue() -> Target {
            return .unknown
        }

    let target: Target

    init(unboxer: Unboxer) {
        self.target = unboxer.unbox("target")
    }
}

let eventDict: UnboxableDictionary = ["target": "mars"]
let event: Event = try! Unbox(eventDict)
```

This code fails with an error saying something along the lines of "invalid value (mars) for key (target)". However I was expecting it to create the `event` with `target = .unknown`, as that is set as the *fallback* value for the enum.

I noticed that in #65 you advice to implement `UnboxableByTransform` on the enum, but then what is the point of having the fallback function at all? Was is its intended purpose? I also noticed the `fallbackValue()` function gets called (in `resolveRequiredValueForKey`) only after the unboxer gets marked as failed. I don't understand that either - why compute the fallback value at all, if `Unbox` is going to throw at the end?

Would you consider changing the behaviour as it seems it's an issue not only for me but for other users of this lib as well?

**Comment by JohnSundell** [comment]
Hi @milancermak,

Happy to hear that you like Unbox & Wrap 🎉 

The `unboxFallbackValue()` method is only used to provide a "dummy" value to a non-optional property, so that Unbox can take care of keeping track of error states, and the model initializers can be kept clean of such logic. It's documented like this:

```
/// The value to use for required properties if unboxing failed. Typically a dummy value.
```

If you want to provide a default value instead of failing, all you have to do is make Swift treat the value as optional, and Unbox won't fail in case it was missing or invalid, like this:

```
class Event: Unboxable {
    init(unboxer: Unboxer) {
        self.target = (unboxer.unbox("target") ?? .unknown)
    }
}
```

**Comment by milancermak** [comment]
Hey John,

thanks for the swift reply 😎 

I know that I can use the `?? defaultValue` idiom and in fact I do in other places of my models.

 However in this case of unboxing the enum value, I expected the `unboxFallbackValue` will be used, exactly because it's a fallback value. That's how I understand the public API of Unbox. Adding a `?? .unknown` is, in my view, an unnecessary repetition.

Even the comment you posted confirms this assumption - at least the first part of it. That it's a dummy value so that Unbox can keep track of errors is IMO an internal implementation detail that should not leak to the public API.

**Comment by JohnSundell** [comment]
It's not always a repetition to use `??` because in various places, because different optional semantics might be desired for the same enum type. So we don't want Unbox to assume that if an enum value failed to Unbox, that the fallback value is a good default. Instead, in some places, the user of the API might want to fail the whole unboxing process instead.

By using the same semantics for enums as for all other types (a Swift optional means that the value is also optional from the perspective of Unbox) - we can maintain a clear and consitent API which uses language scemantics.

`unboxFallbackValue` also needs to be part of the public API, because Unbox enables you to define your own types for unboxing - and there is no way for the framework to "guess" which dummy values to use for custom types.

Perhaps we can further improve the documentation of `unboxFallbackValue()` to include this context? :)

**Comment by samwize** [comment]
I was similarly misled to think that `unboxFallbackValue()` provides the fallback for the enum. Moreover the protocol `UnboxCompatibleType` is mandatory, so naturally I thought "Oh for enum there's always a fallback, so that is no need to make the type optional. Great."
