### ISSUE TITLE
64-bit Integers truncated to 32-bits on 32-bit platforms

### ISSUE THREAD

**Issue by mtviewdave** [JohnSundell/Unbox#80]
64-bit integers are silently truncated to 32-bits on 32-bit platforms, such as the iPhone 4s and 5. E.g.:

`        let bigValue: Int64 = unboxer.unbox("bigValue")
`

"bigValue" will be truncated to 32-bits. On 64-bit platforms (e.g. iPhone 6), I get the expected value.

**Comment by JohnSundell** [comment]
Hi @mtviewdave, how would you like Unbox to behave in this schenario? Should `nil` be returned?

**Comment by mtviewdave** [comment]
I would expect the full 64-bit value would be returned on both 32- and 64-bit platforms.

**Comment by JohnSundell** [comment]
Is that even possible? 😮 How can a 64 bit integer be used on a 32 bit system?

**Comment by mtviewdave** [comment]
Yes, it's possible. Swift Int64 variables work fine on 32-bit systems.  In the Swift runtime, 32- vs 64-bit platforms just refers to the "native word size". The sizeof Int corresponds to the native word size, but Int64 is available on all platforms.

**Comment by JohnSundell** [comment]
That's awesome, didn't know that! Alright, so let's fix this bug :)

**Comment by antwerpenR** [comment]
I can confirm this behaviour - very annoying and still a problem in V1.9

**Comment by JohnSundell** [comment]
@antwerpenR Yeah, know that it still hasn't been fixed - haven't had any time to fix this yet I'm afraid. Understand that it is annoying and will try to fix it asap, in the meantime, feel free to fix it yourself and submit a PR :)

**Comment by antwerpenR** [comment]
@JohnSundell thanks for taking the time to reply and thanks for a truely GREAT JSON parsing framework!  I did work around it so the urgency and motivation to fix it is somewhat reduced but I might look into that PR if/when I get time this week.

**Comment by JohnSundell** [comment]
@antwerpenR Awesome! Would really love a PR, or just if you want to put some code for the workaround here as a comment, and I can integrate it into the framework. Whatever you prefer :) Happy you like Unbox :D

**Comment by antwerpenR** [comment]
@JohnSundell The workaround was really a fix.  I was parsing a date (from meetup.com) which is seconds from 1970.  I parsed into Int which is 64bits on all the new phone/ipads but only 32 on the older devices ....so it overflows and give you a negative number and dates in 1969.   I initially changed my code to use Int64 which OUGHT to have worked on all devices but did not....with a bit more reading I discovered that I really ought to use Double for these dates....so that is what I am doing now.   I guess this info could be useful for test-cases....

**Comment by JohnSundell** [comment]
Sorry for taking a long time to implement this, but I just fixed it on master! 🎉 Will make a `2.1` release with the fix soon.

**Comment by antwerpenR** [comment]
Thanks - you are the BEST.  I understand that you have been busy with the
Spotify HubFramework as well (very nice).   Meanwhile, I am up and running
on your 2.3 build and since I am planning to release to app store in the
coming week or so...I'll postpone any major upgrades for a bit.

Roger (in HK)

Roger Price
GSM: +852-6978-3655
http://antwerpenR.com

**Comment by JohnSundell** [comment]
@antwerpenR 🎉 Sounds good - let me know if my fix works for you once you've upgraded :)

**Comment by JohnSundell** [comment]
Has now been released! 🚀 https://github.com/JohnSundell/Unbox/releases/tag/2.1
