### ISSUE TITLE
NSCoding Support

### ISSUE THREAD

**Issue by Ashu** [JohnSundell/Unbox#82]
Can we store Unboxable object to the persistent storage?

**Comment by JohnSundell** [comment]
Hey @Ashu, you can totally use Unbox to store objects in persistent storage, using JSON, a plist or any other `Dictionary` or `NSData`-based format. Unbox itself doesn't contain any `NSCoding` support per se, since it's a JSON framework, and `NSCoding` uses Apple's own binary format to store object snapshots on disk.

But you can very easily unbox `NSData` that has been persisted on disk using Unbox (and you could use [https://github.com/johnsundell/wrap](Wrap) to serialize it).

**Comment by giladronat** [comment]
Hey @JohnSundell, when trying to persist simple models to disk, would you recommend persisting the JSON as `NSData` instead of `NSCoding`? 

As far as a generic, saves-you-from-boilerplate `NSCoding` solution, I feel like having a nice way to bridge property names and `NSCoding` storage keys in the same library as the one that determines those property names would be handy. I think this is why @Ashu is asking, and I'd love to see that too as opposed to pull another dependency. 

I'm more so interested in your reasoning and fostering a discussion than compelling you to build this into the framework.
