### ISSUE TITLE
Proposal: `Boxable`, Model => JSON serialization.

### ISSUE THREAD

**Issue by ldiqual** [JohnSundell/Unbox#88]
Proposal: `Boxable`, Model => JSON serialization.
======================================================

@JohnSundell Here's a proposal for adding a `Boxable` protocol and a `Boxer` class that would handle Model => JSON serialization.

Motivation
----------

During the migration of the Scoop app to Swift 3.0, we had to shift from ObjectMapper to Unbox because of the poor support for non-optional properties. [IUOs](https://github.com/apple/swift-evolution/blob/master/proposals/0054-abolish-iuo.md) started to show as `Optional(something)` in the UI and we had to unwrap every single property of our models everywhere in our screens.

Migrating to Unbox has been mostly a joy, unboxing (JSON => model) was easy and straightforward. However we had to had to write our own boxing (model => JSON) code, which turned out to be pretty bug-prone. More specifically, it was a bit tough to handle serialization of nested objects, null values (which should be NSNull() or missing, depending on the context), or special types like NSDate.

So we thought it would be a good idea to contribute back to the community with such a serializer. But before we start implementing, we'd like to make sure such a feature fits the goal of Unbox.

Here's a rough idea of what `Boxable` would look like.

Protocol
--------

```
protocol Boxable {
    func box(boxer: Boxer) throws
}
```

Compliance
----------

```
class Article: Boxable {

    let title: String
    let createdAt: NSDate
    let nestedField: String
    let comments: [Comment] // Comment is Boxable

    func box(boxer: Boxer) throws {
        boxer.box("title", title)
        boxer.box("createdAt", createdAt, formatter: NSDateFormatter())
        boxer.box("nested.field", nestedField, isKeyPath: true)
        boxer.box("comments", comments)
    }    
}
```

Usage
-----

```
let dict = try Box(object)
```

Additional notes
----------------

 - `Box` could take optional arguments such as `serializeNull = true`
 - `Box` could also serialize arrays with `Box.array([Boxable])` to avoid awkwardness around `map` and throwables
 - `box()` could throw if a property is not serializable. This error would potentially be thrown directly by the end user in the `box()` implementation, probably not by the library itself since it'll check for serialization capability at compilation time.
 - `Boxer` would infer the serialization logic from the provide argument type. Think lots of generics, like in the `Unbox` implementation. Custom serialization could be provided via `BoxableByTransform`.
 - My first thought on the feature implementation would be to use [SwiftyJSON](https://github.com/SwiftyJSON/SwiftyJSON) to ease the serialization. We've been using this library for a while and it turned out to be very reliable. This would add an extra dependency though, not sure you wanna go this way.

Questions
---------

 - Is this something that you think could be a valuable addition to Unbox, or should this be a separate library?
 - What do you think about `Boxable`, `Boxer`, and `Box` (on the interface/usage level)?

**Comment by JohnSundell** [comment]
Hi @ldiqual, happy to hear that it was easy to migrate to Unbox - and thanks for the very thorough proposal! Thankfully, I created [Wrap](https://github.com/johnsundell/wrap) for this very reason - it's Unbox's equivalent on the serialization side, and provides all the features (except for `serializeNull = true`, but we could add that) that you request.

Even better, it does so with very little code on your part, since it uses Swift's reflection API to automatically encode all of your objects and their values. There's also customization options, just like for Unbox.

Check out Wrap and let me know what you think :)

(I should probably advertise that Wrap exists in Unbox's Readme, come to think of it) :)

**Comment by ldiqual** [comment]
@JohnSundell Thanks! I'll take a look at Wrap. Weird that it didn't show in my search results about serializing models in Swift. Probably worth closing now ;) Thanks again!

**Comment by eliburke** [comment]
You should definitely update the README to mention Wrap. I saw it mentioned once before but was not clued in to the fact that it was a standalone project until I read this issue.

**Comment by ldiqual** [comment]
@JohnSundell Fyi after evaluating whether to add `Wrap` in our codebase, we decided to go against it because we're not big fans of the magic associated with the property => json key serialization, which I assume uses mirroring behind the scenes.
A lot of the keys between models & json differ, and we also use a bunch of key paths that don't use nested models. I really wish `Wrap` had a syntax that's closer to `Unbox` with less magic and without the `keyForWrapping` layer of indirection, something more like my proposal above.

**Comment by JohnSundell** [comment]
@eliburke Yeah, I will! Forgot about it, but will definetly do it - thanks! 👍

**Comment by JohnSundell** [comment]
@ldiqual I know whether or not to use Reflection to implement things like serialization (as Wrap does) is a very polarizing issue. I personally don't see it as "magic" as long as its properly documented, tested and uses official APIs.

I must admit that it's more explicit to do the mapping "manually", instead of relying on an automated solution, but IMO it's also way more error prone. It's easy to run into bugs when the serialization code is accidentally not updated, which can lead to data inconsistencies. Unit tests, etc can of course solve this - to some extent - but in terms of both serialization and copying code - I really prefer automating it 🙂 

So I'm personally not going to make a more "Unbox-like" serialization library anytime soon, but would love to see something like what you propose from either you or anyone else in the community who prefers to do serialization this way - multiple solutions that cater to different preferences are always a good thing for the community 🚀
